
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erik
 */
import java.awt.Color;
import java.util.*;
import se.chalmers.ait.dat215.project.*;
public class categoryViewPanel extends javax.swing.JPanel {
    IMatDataHandler dh = IMatDataHandler.getInstance();
    /**
     * Creates new form categoryViewPanel
     */
    public categoryViewPanel() {
        initComponents();
    }
    public categoryViewPanel(ProductCategory[] categorys, String name){
        initComponents();
        setComponents(categorys, name);
        
    }
    public void setComponents(ProductCategory[] categorys, String name){
        categoryNameLabel.setText(name);
        ArrayList<Product> products = new ArrayList<Product>();
        for(ProductCategory s: categorys){
            products.addAll(dh.getProducts(s));
        }
        System.out.println(products.size());
        boolean background = false;
        for(Product p: products){
            itemContainerPanel.add(new itemPanel(p,background));
            background = !background;
            System.out.println(p.getName());
        }
        itemContainerPanel.setBackground(Color.GREEN);
    }
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryNameLabel = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemContainerPanel = new javax.swing.JPanel();

        categoryNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        categoryNameLabel.setText("jLabel1");

        itemContainerPanel.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(itemContainerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categoryNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(categoryNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryNameLabel;
    private javax.swing.JPanel itemContainerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
