
import java.awt.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sebastian
 */
public class checkOutPanel extends javax.swing.JPanel {

    /**
     * Creates new form checkOutPanel
     */
    public checkOutPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheckOutStage2RadioButtonGroup = new javax.swing.ButtonGroup();
        paymentRadioButtonGroup = new javax.swing.ButtonGroup();
        checkOutStage1Panel = new javax.swing.JPanel();
        titleLabel1 = new javax.swing.JLabel();
        firstNameLabel1 = new javax.swing.JLabel();
        firstNameTextFieldl1 = new javax.swing.JTextField();
        lastNameLabel1 = new javax.swing.JLabel();
        lastNameTextField1 = new javax.swing.JTextField();
        adressLabel1 = new javax.swing.JLabel();
        adressTextField1 = new javax.swing.JTextField();
        zipCodeLabel1 = new javax.swing.JLabel();
        zipCodeTextField1 = new javax.swing.JTextField();
        cityLabel1 = new javax.swing.JLabel();
        cityTextField1 = new javax.swing.JTextField();
        phoneLabel1 = new javax.swing.JLabel();
        phoneTextField1 = new javax.swing.JTextField();
        emailLabel1 = new javax.swing.JLabel();
        emailTextField1 = new javax.swing.JTextField();
        totalPriceLabel1 = new javax.swing.JLabel();
        totalPriceNumberLabel1 = new javax.swing.JLabel();
        stepLabel1 = new javax.swing.JLabel();
        nextButton1 = new javax.swing.JButton();
        paymentPanel = new javax.swing.JPanel();
        cardPaymentPanel = new javax.swing.JPanel();
        cardNumberTextField = new javax.swing.JTextField();
        cardMonthComboBox = new javax.swing.JComboBox();
        cardYearComboBox = new javax.swing.JComboBox();
        cardSecurityCodeTextField = new javax.swing.JTextField();
        cardExpirationLabel = new javax.swing.JLabel();
        invoicePaymentPanel = new javax.swing.JPanel();
        personalNumberTextField = new javax.swing.JTextField();
        personalNumberLabel = new javax.swing.JLabel();
        cardPaymentRadioButton = new javax.swing.JRadioButton();
        invoicePaymentRadioButton = new javax.swing.JRadioButton();
        checkOutStage2Panel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextFieldl = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        adressLabel = new javax.swing.JLabel();
        adressTextField = new javax.swing.JTextField();
        zipCodeLabel = new javax.swing.JLabel();
        zipCodeTextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        totalPriceLabel = new javax.swing.JLabel();
        totalPriceNumberLabel = new javax.swing.JLabel();
        stepLabel = new javax.swing.JLabel();
        sameAdressRadioButton = new javax.swing.JRadioButton();
        newAdressRadioButton = new javax.swing.JRadioButton();
        nextButton = new javax.swing.JButton();
        checkOutStage3Panel = new javax.swing.JPanel();
        titleLabel2 = new javax.swing.JLabel();
        totalPriceLabel2 = new javax.swing.JLabel();
        totalPriceNumberLabel2 = new javax.swing.JLabel();
        stepLabel2 = new javax.swing.JLabel();
        nextButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(981, 326));
        setLayout(new java.awt.CardLayout());

        checkOutStage1Panel.setBackground(new java.awt.Color(255, 255, 255));
        checkOutStage1Panel.setForeground(new java.awt.Color(255, 255, 255));
        checkOutStage1Panel.setPreferredSize(new java.awt.Dimension(981, 315));

        titleLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel1.setText("Fakturaadress");

        firstNameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        firstNameLabel1.setText("Förnamn");

        lastNameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lastNameLabel1.setText("Efternamn");

        adressLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        adressLabel1.setText("Adress");

        zipCodeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        zipCodeLabel1.setText("Post nummer");

        cityLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cityLabel1.setText("Stad");

        phoneLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        phoneLabel1.setText("Telefon nummer");

        emailLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        emailLabel1.setText("Epost");

        totalPriceLabel1.setText("Totalt Pris");

        totalPriceNumberLabel1.setText("0:-");

        stepLabel1.setText("Steg 1 av 3");

        nextButton1.setText("Nästa");
        nextButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButton1ActionPerformed(evt);
            }
        });

        paymentPanel.setLayout(new java.awt.CardLayout());

        cardPaymentPanel.setToolTipText("Kort betalning");

        cardNumberTextField.setText("Kortnummer");

        cardMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Månad", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cardYearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "År", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027" }));
        cardYearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardYearComboBoxActionPerformed(evt);
            }
        });

        cardSecurityCodeTextField.setText("Säkerhetskod");

        cardExpirationLabel.setText("Giltig till");

        javax.swing.GroupLayout cardPaymentPanelLayout = new javax.swing.GroupLayout(cardPaymentPanel);
        cardPaymentPanel.setLayout(cardPaymentPanelLayout);
        cardPaymentPanelLayout.setHorizontalGroup(
            cardPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPaymentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardSecurityCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPaymentPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(cardExpirationLabel)
                .addGap(18, 18, 18)
                .addComponent(cardMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardPaymentPanelLayout.setVerticalGroup(
            cardPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPaymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardSecurityCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(cardPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardExpirationLabel))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        paymentPanel.add(cardPaymentPanel, "cardCard");

        invoicePaymentPanel.setToolTipText("Faktura betalning");

        personalNumberTextField.setText("ÅÅÅÅ-MM-DD-NNNN");

        personalNumberLabel.setText("Personnummer");

        javax.swing.GroupLayout invoicePaymentPanelLayout = new javax.swing.GroupLayout(invoicePaymentPanel);
        invoicePaymentPanel.setLayout(invoicePaymentPanelLayout);
        invoicePaymentPanelLayout.setHorizontalGroup(
            invoicePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicePaymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personalNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personalNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        invoicePaymentPanelLayout.setVerticalGroup(
            invoicePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicePaymentPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(invoicePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personalNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personalNumberLabel))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        paymentPanel.add(invoicePaymentPanel, "invoiceCard");

        paymentRadioButtonGroup.add(cardPaymentRadioButton);
        cardPaymentRadioButton.setSelected(true);
        cardPaymentRadioButton.setText("Kortbetalning");
        cardPaymentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardPaymentRadioButtonActionPerformed(evt);
            }
        });

        paymentRadioButtonGroup.add(invoicePaymentRadioButton);
        invoicePaymentRadioButton.setText("Faktura");
        invoicePaymentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoicePaymentRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkOutStage1PanelLayout = new javax.swing.GroupLayout(checkOutStage1Panel);
        checkOutStage1Panel.setLayout(checkOutStage1PanelLayout);
        checkOutStage1PanelLayout.setHorizontalGroup(
            checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutStage1PanelLayout.createSequentialGroup()
                .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nextButton1)
                            .addComponent(stepLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zipCodeLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cityLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adressLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailTextField1)
                            .addComponent(lastNameTextField1)
                            .addComponent(adressTextField1)
                            .addComponent(phoneTextField1)
                            .addComponent(cityTextField1)
                            .addComponent(zipCodeTextField1)
                            .addComponent(firstNameTextFieldl1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                                .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(totalPriceLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalPriceNumberLabel1))
                            .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                                .addComponent(cardPaymentRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(invoicePaymentRadioButton)))))
                .addGap(31, 31, 31))
            .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        checkOutStage1PanelLayout.setVerticalGroup(
            checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalPriceLabel1)
                        .addComponent(totalPriceNumberLabel1))
                    .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel1)
                            .addComponent(firstNameTextFieldl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel1)
                            .addComponent(lastNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adressLabel1)
                            .addComponent(adressTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zipCodeLabel1)
                            .addComponent(zipCodeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityLabel1)
                            .addComponent(cityTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel1)
                            .addComponent(phoneTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel1)
                            .addComponent(emailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cardPaymentRadioButton)
                            .addComponent(invoicePaymentRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stepLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton1)
                .addGap(20, 20, 20))
        );

        add(checkOutStage1Panel, "card2");

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Leveransadress");

        firstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        firstNameLabel.setText("Förnamn");

        firstNameTextFieldl.setText("jTextField1");

        lastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lastNameLabel.setText("Efternamn");

        lastNameTextField.setText("jTextField1");

        adressLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        adressLabel.setText("Adress");

        adressTextField.setText("jTextField1");

        zipCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        zipCodeLabel.setText("Post nummer");

        zipCodeTextField.setText("jTextField1");

        cityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cityLabel.setText("Stad");

        cityTextField.setText("jTextField1");

        phoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        phoneLabel.setText("Telefon nummer");

        phoneTextField.setText("jTextField1");

        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        emailLabel.setText("Epost");

        emailTextField.setText("jTextField1");

        totalPriceLabel.setText("Totalt Pris");

        totalPriceNumberLabel.setText("0:-");

        stepLabel.setText("Steg 2 av 3");

        CheckOutStage2RadioButtonGroup.add(sameAdressRadioButton);
        sameAdressRadioButton.setSelected(true);
        sameAdressRadioButton.setText("Samma ");

        CheckOutStage2RadioButtonGroup.add(newAdressRadioButton);
        newAdressRadioButton.setText("Ny adress");

        nextButton.setText("Nästa");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkOutStage2PanelLayout = new javax.swing.GroupLayout(checkOutStage2Panel);
        checkOutStage2Panel.setLayout(checkOutStage2PanelLayout);
        checkOutStage2PanelLayout.setHorizontalGroup(
            checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutStage2PanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(checkOutStage2PanelLayout.createSequentialGroup()
                        .addComponent(sameAdressRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(newAdressRadioButton))
                    .addGroup(checkOutStage2PanelLayout.createSequentialGroup()
                        .addGroup(checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zipCodeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailTextField)
                            .addComponent(lastNameTextField)
                            .addComponent(adressTextField)
                            .addComponent(phoneTextField)
                            .addComponent(cityTextField)
                            .addComponent(zipCodeTextField)
                            .addComponent(firstNameTextFieldl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 598, Short.MAX_VALUE)
                .addGroup(checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutStage2PanelLayout.createSequentialGroup()
                        .addComponent(totalPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPriceNumberLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nextButton)
                        .addComponent(stepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutStage2PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        checkOutStage2PanelLayout.setVerticalGroup(
            checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkOutStage2PanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkOutStage2PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalPriceLabel)
                            .addComponent(totalPriceNumberLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stepLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutStage2PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newAdressRadioButton)
                            .addComponent(sameAdressRadioButton))
                        .addGap(18, 18, 18)
                        .addGroup(checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel)
                            .addComponent(firstNameTextFieldl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adressLabel)
                            .addComponent(adressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zipCodeLabel)
                            .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityLabel)
                            .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkOutStage2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );

        firstNameLabel.getAccessibleContext().setAccessibleDescription("");
        firstNameTextFieldl.getAccessibleContext().setAccessibleDescription("");
        lastNameLabel.getAccessibleContext().setAccessibleDescription("");
        lastNameTextField.getAccessibleContext().setAccessibleDescription("");
        adressLabel.getAccessibleContext().setAccessibleDescription("");
        adressTextField.getAccessibleContext().setAccessibleDescription("");
        zipCodeLabel.getAccessibleContext().setAccessibleDescription("");
        zipCodeTextField.getAccessibleContext().setAccessibleDescription("");
        cityLabel.getAccessibleContext().setAccessibleDescription("");
        cityTextField.getAccessibleContext().setAccessibleDescription("");
        phoneLabel.getAccessibleContext().setAccessibleDescription("");
        phoneTextField.getAccessibleContext().setAccessibleDescription("");
        emailLabel.getAccessibleContext().setAccessibleDescription("");
        emailTextField.getAccessibleContext().setAccessibleDescription("");
        totalPriceLabel.getAccessibleContext().setAccessibleDescription("");
        totalPriceNumberLabel.getAccessibleContext().setAccessibleDescription("");
        stepLabel.getAccessibleContext().setAccessibleDescription("");
        sameAdressRadioButton.getAccessibleContext().setAccessibleDescription("");
        newAdressRadioButton.getAccessibleContext().setAccessibleDescription("");

        add(checkOutStage2Panel, "card2");

        checkOutStage3Panel.setPreferredSize(new java.awt.Dimension(981, 315));

        titleLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel2.setText("Leveransdatum");

        totalPriceLabel2.setText("Totalt Pris");

        totalPriceNumberLabel2.setText("0:-");

        stepLabel2.setText("Steg 3 av 3");

        nextButton2.setText("Betala");

        jRadioButton1.setText("Snarast (inom 48h)");

        jRadioButton2.setText("jRadioButton2");

        jRadioButton3.setText("08-11");

        jRadioButton4.setText("11-14");

        jRadioButton5.setText("14-17");

        jRadioButton6.setText("17-21");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Leveransdag");

        jLabel2.setText("Tid på dygnet");

        jLabel3.setText("Morgon");

        jLabel4.setText("Lunch");

        jLabel5.setText("Eftermiddag");

        jLabel7.setText("Kväll");

        javax.swing.GroupLayout checkOutStage3PanelLayout = new javax.swing.GroupLayout(checkOutStage3Panel);
        checkOutStage3Panel.setLayout(checkOutStage3PanelLayout);
        checkOutStage3PanelLayout.setHorizontalGroup(
            checkOutStage3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutStage3PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(checkOutStage3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(checkOutStage3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nextButton2)
                        .addComponent(stepLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(checkOutStage3PanelLayout.createSequentialGroup()
                        .addGroup(checkOutStage3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton6)
                            .addComponent(totalPriceLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPriceNumberLabel2)))
                .addGap(31, 31, 31))
            .addGroup(checkOutStage3PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutStage3PanelLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(checkOutStage3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addGroup(checkOutStage3PanelLayout.createSequentialGroup()
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
            .addGroup(checkOutStage3PanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(checkOutStage3PanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(checkOutStage3PanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(checkOutStage3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(checkOutStage3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkOutStage3PanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7))
                    .addComponent(jRadioButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutStage3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        checkOutStage3PanelLayout.setVerticalGroup(
            checkOutStage3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkOutStage3PanelLayout.createSequentialGroup()
                .addComponent(titleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkOutStage3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkOutStage3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkOutStage3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(42, 42, 42)
                .addGroup(checkOutStage3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPriceLabel2)
                    .addComponent(totalPriceNumberLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stepLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton2)
                .addGap(20, 20, 20))
        );

        add(checkOutStage3Panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void nextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton1ActionPerformed
        //Switch card to the next one
        CardLayout cl = (CardLayout)(this.getLayout());
        cl.next(this);// TODO add your handling code here:
    }//GEN-LAST:event_nextButton1ActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        nextButton1ActionPerformed(evt); //Switches card to the next one
    }//GEN-LAST:event_nextButtonActionPerformed

    private void cardYearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardYearComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardYearComboBoxActionPerformed

    private void cardPaymentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardPaymentRadioButtonActionPerformed
        CardLayout cl = (CardLayout) (paymentPanel.getLayout());
        cl.show(paymentPanel, "cardCard");// TODO add your handling code here:
    }//GEN-LAST:event_cardPaymentRadioButtonActionPerformed

    private void invoicePaymentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoicePaymentRadioButtonActionPerformed
        CardLayout cl = (CardLayout) (paymentPanel.getLayout());
        cl.show(paymentPanel, "invoiceCard");// TODO add your handling code here:
    }//GEN-LAST:event_invoicePaymentRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup CheckOutStage2RadioButtonGroup;
    private javax.swing.JLabel adressLabel;
    private javax.swing.JLabel adressLabel1;
    private javax.swing.JTextField adressTextField;
    private javax.swing.JTextField adressTextField1;
    private javax.swing.JLabel cardExpirationLabel;
    private javax.swing.JComboBox cardMonthComboBox;
    private javax.swing.JTextField cardNumberTextField;
    private javax.swing.JPanel cardPaymentPanel;
    private javax.swing.JRadioButton cardPaymentRadioButton;
    private javax.swing.JTextField cardSecurityCodeTextField;
    private javax.swing.JComboBox cardYearComboBox;
    private javax.swing.JPanel checkOutStage1Panel;
    private javax.swing.JPanel checkOutStage2Panel;
    private javax.swing.JPanel checkOutStage3Panel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel cityLabel1;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField cityTextField1;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameLabel1;
    private javax.swing.JTextField firstNameTextFieldl;
    private javax.swing.JTextField firstNameTextFieldl1;
    private javax.swing.JPanel invoicePaymentPanel;
    private javax.swing.JRadioButton invoicePaymentRadioButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lastNameLabel1;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField lastNameTextField1;
    private javax.swing.JRadioButton newAdressRadioButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton nextButton1;
    private javax.swing.JButton nextButton2;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.ButtonGroup paymentRadioButtonGroup;
    private javax.swing.JLabel personalNumberLabel;
    private javax.swing.JTextField personalNumberTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel phoneLabel1;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField phoneTextField1;
    private javax.swing.JRadioButton sameAdressRadioButton;
    private javax.swing.JLabel stepLabel;
    private javax.swing.JLabel stepLabel1;
    private javax.swing.JLabel stepLabel2;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel titleLabel2;
    private javax.swing.JLabel totalPriceLabel;
    private javax.swing.JLabel totalPriceLabel1;
    private javax.swing.JLabel totalPriceLabel2;
    private javax.swing.JLabel totalPriceNumberLabel;
    private javax.swing.JLabel totalPriceNumberLabel1;
    private javax.swing.JLabel totalPriceNumberLabel2;
    private javax.swing.JLabel zipCodeLabel;
    private javax.swing.JLabel zipCodeLabel1;
    private javax.swing.JTextField zipCodeTextField;
    private javax.swing.JTextField zipCodeTextField1;
    // End of variables declaration//GEN-END:variables
}
