

import java.awt.*;
import java.awt.event.ItemEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import se.chalmers.ait.dat215.project.CreditCard;
import se.chalmers.ait.dat215.project.Customer;
import se.chalmers.ait.dat215.project.IMatDataHandler;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sebastian
 */
public class checkOutPanel extends javax.swing.JPanel {
   
    
    IMatDataHandler iMatShared = IMatDataHandler.getInstance();
    CreditCard cc = iMatShared.getCreditCard();
    Customer customer = iMatShared.getCustomer();
    /**
     * Creates new form checkOutPanel
     */
    public checkOutPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deliveryAdressRadioButtonGroup = new javax.swing.ButtonGroup();
        paymentRadioButtonGroup = new javax.swing.ButtonGroup();
        dayOfDeliveryRadioButtonGroup = new javax.swing.ButtonGroup();
        timeOfDayRadioButtonGroup = new javax.swing.ButtonGroup();
        checkOutStage1Panel = new javax.swing.JPanel();
        billingTitleLabel = new javax.swing.JLabel();
        deliveryTimePanel = new javax.swing.JPanel();
        asSoonAsPossibleDeliveryRadioButton = new javax.swing.JRadioButton();
        chooseDayDeliveryRadioButton = new javax.swing.JRadioButton();
        morningDeliveryRadioButton = new javax.swing.JRadioButton();
        lunchDeliveryRadioButton = new javax.swing.JRadioButton();
        afternoonDeliveryRadioButton = new javax.swing.JRadioButton();
        eveningRadioButton = new javax.swing.JRadioButton();
        dayDeliveryComboBox = new javax.swing.JComboBox();
        monthDeliveryComboBox = new javax.swing.JComboBox();
        deliveryDayLabel = new javax.swing.JLabel();
        timeOfDayLabel = new javax.swing.JLabel();
        morningLabel = new javax.swing.JLabel();
        lunchLabel = new javax.swing.JLabel();
        afternoonLabel = new javax.swing.JLabel();
        eveningLabel = new javax.swing.JLabel();
        billingFirstNameLabel = new javax.swing.JLabel();
        billingFirstNameTextField = new javax.swing.JTextField();
        billingLastNameLabel = new javax.swing.JLabel();
        billingLastNameTextField = new javax.swing.JTextField();
        billingAdressLabel = new javax.swing.JLabel();
        billingAdressTextField = new javax.swing.JTextField();
        billingZipCodeLabel = new javax.swing.JLabel();
        billingZipCodeTextField = new javax.swing.JTextField();
        billingCityLabel = new javax.swing.JLabel();
        billingCityTextField = new javax.swing.JTextField();
        billingPhoneLabel = new javax.swing.JLabel();
        billingPhoneTextField = new javax.swing.JTextField();
        billingEmailLabel = new javax.swing.JLabel();
        billingEmailTextField = new javax.swing.JTextField();
        TotalPriceLabel = new javax.swing.JLabel();
        totalPriceNumberLabel = new javax.swing.JLabel();
        payButton = new javax.swing.JButton();
        paymentPanel = new javax.swing.JPanel();
        cardPaymentPanel = new javax.swing.JPanel();
        cardNumberTextField = new javax.swing.JTextField();
        cardMonthComboBox = new javax.swing.JComboBox();
        cardYearComboBox = new javax.swing.JComboBox();
        cardSecurityCodeTextField = new javax.swing.JTextField();
        cardExpirationLabel = new javax.swing.JLabel();
        invoicePaymentPanel = new javax.swing.JPanel();
        personalNumberTextField = new javax.swing.JTextField();
        personalNumberLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        cardPaymentRadioButton = new javax.swing.JRadioButton();
        invoicePaymentRadioButton = new javax.swing.JRadioButton();
        deliveryEmailTextField = new javax.swing.JTextField();
        deliveryPhoneTextField = new javax.swing.JTextField();
        deliveryCityTextField = new javax.swing.JTextField();
        deliveryZipCodeTextField = new javax.swing.JTextField();
        deliveryAdressTextField = new javax.swing.JTextField();
        deliveryLastNameTextField = new javax.swing.JTextField();
        deliveryFirstNameTextField = new javax.swing.JTextField();
        newAdressRadioButton = new javax.swing.JRadioButton();
        sameAdressRadioButton = new javax.swing.JRadioButton();
        deliveryFirstNameLabel = new javax.swing.JLabel();
        deliveryLastNameLabel = new javax.swing.JLabel();
        deliveryAdressLabel = new javax.swing.JLabel();
        deliveryZipCodeLabel = new javax.swing.JLabel();
        deliveryCityLabel = new javax.swing.JLabel();
        deliveryPhoneLabel = new javax.swing.JLabel();
        deliveryEmailLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(981, 660));
        setPreferredSize(new java.awt.Dimension(981, 326));
        setLayout(new java.awt.CardLayout());

        checkOutStage1Panel.setBackground(new java.awt.Color(255, 252, 243));
        checkOutStage1Panel.setForeground(new java.awt.Color(255, 255, 255));
        checkOutStage1Panel.setMaximumSize(new java.awt.Dimension(981, 700));
        checkOutStage1Panel.setMinimumSize(new java.awt.Dimension(981, 660));
        checkOutStage1Panel.setPreferredSize(new java.awt.Dimension(981, 660));

        billingTitleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        billingTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billingTitleLabel.setText("Betalningsadress");

        deliveryTimePanel.setBackground(new java.awt.Color(229, 240, 255));
        deliveryTimePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deliveryTimePanel.setMaximumSize(new java.awt.Dimension(400, 198));
        deliveryTimePanel.setPreferredSize(new java.awt.Dimension(400, 198));

        asSoonAsPossibleDeliveryRadioButton.setBackground(new java.awt.Color(229, 240, 255));
        dayOfDeliveryRadioButtonGroup.add(asSoonAsPossibleDeliveryRadioButton);
        asSoonAsPossibleDeliveryRadioButton.setSelected(true);
        asSoonAsPossibleDeliveryRadioButton.setText("Snarast (inom 48h)");

        chooseDayDeliveryRadioButton.setBackground(new java.awt.Color(229, 240, 255));
        dayOfDeliveryRadioButtonGroup.add(chooseDayDeliveryRadioButton);

        morningDeliveryRadioButton.setBackground(new java.awt.Color(229, 240, 255));
        timeOfDayRadioButtonGroup.add(morningDeliveryRadioButton);
        morningDeliveryRadioButton.setSelected(true);
        morningDeliveryRadioButton.setText("08-11");

        lunchDeliveryRadioButton.setBackground(new java.awt.Color(229, 240, 255));
        timeOfDayRadioButtonGroup.add(lunchDeliveryRadioButton);
        lunchDeliveryRadioButton.setText("11-14");

        afternoonDeliveryRadioButton.setBackground(new java.awt.Color(229, 240, 255));
        timeOfDayRadioButtonGroup.add(afternoonDeliveryRadioButton);
        afternoonDeliveryRadioButton.setText("14-17");

        eveningRadioButton.setBackground(new java.awt.Color(229, 240, 255));
        timeOfDayRadioButtonGroup.add(eveningRadioButton);
        eveningRadioButton.setText("17-21");

        dayDeliveryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dag", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "25", "26", "27", "28", "29", "30", "31" }));

        monthDeliveryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Månad", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        deliveryDayLabel.setText("Leveransdag");

        timeOfDayLabel.setText("Tid på dygnet");

        morningLabel.setText("Morgon");

        lunchLabel.setText("Lunch");

        afternoonLabel.setText("Eftermiddag");

        eveningLabel.setText("Kväll");

        javax.swing.GroupLayout deliveryTimePanelLayout = new javax.swing.GroupLayout(deliveryTimePanel);
        deliveryTimePanel.setLayout(deliveryTimePanelLayout);
        deliveryTimePanelLayout.setHorizontalGroup(
            deliveryTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryTimePanelLayout.createSequentialGroup()
                .addGroup(deliveryTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryTimePanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(timeOfDayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deliveryTimePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(morningDeliveryRadioButton)
                        .addGap(17, 17, 17)
                        .addGroup(deliveryTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deliveryTimePanelLayout.createSequentialGroup()
                                .addComponent(dayDeliveryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthDeliveryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(deliveryTimePanelLayout.createSequentialGroup()
                                .addComponent(lunchDeliveryRadioButton)
                                .addGap(14, 14, 14)
                                .addComponent(afternoonDeliveryRadioButton)
                                .addGap(19, 19, 19)
                                .addComponent(eveningRadioButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(deliveryTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deliveryTimePanelLayout.createSequentialGroup()
                    .addGroup(deliveryTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(deliveryTimePanelLayout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addGroup(deliveryTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(asSoonAsPossibleDeliveryRadioButton)
                                .addComponent(chooseDayDeliveryRadioButton)))
                        .addGroup(deliveryTimePanelLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(deliveryDayLabel))
                        .addGroup(deliveryTimePanelLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(morningLabel))
                        .addGroup(deliveryTimePanelLayout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(lunchLabel)
                            .addGap(42, 42, 42)
                            .addComponent(afternoonLabel)
                            .addGap(30, 30, 30)
                            .addComponent(eveningLabel)))
                    .addContainerGap(37, Short.MAX_VALUE)))
        );
        deliveryTimePanelLayout.setVerticalGroup(
            deliveryTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliveryTimePanelLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(deliveryTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayDeliveryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthDeliveryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timeOfDayLabel)
                .addGap(31, 31, 31)
                .addGroup(deliveryTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eveningRadioButton)
                    .addComponent(morningDeliveryRadioButton)
                    .addComponent(lunchDeliveryRadioButton)
                    .addComponent(afternoonDeliveryRadioButton))
                .addGap(17, 17, 17))
            .addGroup(deliveryTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deliveryTimePanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(deliveryDayLabel)
                    .addGap(4, 4, 4)
                    .addComponent(asSoonAsPossibleDeliveryRadioButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chooseDayDeliveryRadioButton)
                    .addGap(44, 44, 44)
                    .addGroup(deliveryTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(morningLabel)
                        .addComponent(lunchLabel)
                        .addComponent(eveningLabel)
                        .addComponent(afternoonLabel))
                    .addContainerGap(44, Short.MAX_VALUE)))
        );

        billingFirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        billingFirstNameLabel.setText("Förnamn");

        billingFirstNameTextField.setText(customer.getFirstName());
        billingFirstNameTextField.setNextFocusableComponent(billingLastNameTextField);
        billingFirstNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                billingFirstNameTextFieldFocusLost(evt);
            }
        });

        billingLastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        billingLastNameLabel.setText("Efternamn");

        billingLastNameTextField.setText(customer.getLastName());
        billingLastNameTextField.setNextFocusableComponent(billingAdressTextField);
        billingLastNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                billingLastNameTextFieldFocusLost(evt);
            }
        });

        billingAdressLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        billingAdressLabel.setText("Adress");

        billingAdressTextField.setText(customer.getAddress());
        billingAdressTextField.setNextFocusableComponent(billingZipCodeTextField);
        billingAdressTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                billingAdressTextFieldFocusLost(evt);
            }
        });

        billingZipCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        billingZipCodeLabel.setText("Post nummer");

        billingZipCodeTextField.setText(customer.getPostCode());
        billingZipCodeTextField.setNextFocusableComponent(billingCityTextField);
        billingZipCodeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                billingZipCodeTextFieldFocusLost(evt);
            }
        });

        billingCityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        billingCityLabel.setText("Stad");

        billingCityTextField.setText(customer.getPostAddress());
        billingCityTextField.setNextFocusableComponent(billingPhoneTextField);
        billingCityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                billingCityTextFieldFocusLost(evt);
            }
        });

        billingPhoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        billingPhoneLabel.setText("Telefon nummer");

        billingPhoneTextField.setText(customer.getPhoneNumber());
        billingPhoneTextField.setNextFocusableComponent(billingEmailTextField);
        billingPhoneTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                billingPhoneTextFieldFocusLost(evt);
            }
        });

        billingEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        billingEmailLabel.setText("Epost");

        billingEmailTextField.setText(customer.getEmail());
        billingEmailTextField.setNextFocusableComponent(sameAdressRadioButton);
        billingEmailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                billingEmailTextFieldFocusLost(evt);
            }
        });

        TotalPriceLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TotalPriceLabel.setText("Totalt Pris");

        totalPriceNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalPriceNumberLabel.setText(totalPrice() + ":-");
        totalPriceNumberLabel.setToolTipText("");

        payButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        payButton.setText("Betala");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        paymentPanel.setLayout(new java.awt.CardLayout());

        cardPaymentPanel.setBackground(new java.awt.Color(229, 240, 255));
        cardPaymentPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cardPaymentPanel.setToolTipText("Kort betalning");

        cardNumberTextField.setText("******KORTNUMMER*****");
        cardNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardNumberTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cardNumberTextFieldFocusLost(evt);
            }
        });

        cardMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Månad", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cardYearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "År", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027" }));
        cardYearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardYearComboBoxActionPerformed(evt);
            }
        });

        cardSecurityCodeTextField.setText("***CVV****");
        cardSecurityCodeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardSecurityCodeTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cardSecurityCodeTextFieldFocusLost(evt);
            }
        });

        cardExpirationLabel.setText("Giltig till");

        javax.swing.GroupLayout cardPaymentPanelLayout = new javax.swing.GroupLayout(cardPaymentPanel);
        cardPaymentPanel.setLayout(cardPaymentPanelLayout);
        cardPaymentPanelLayout.setHorizontalGroup(
            cardPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPaymentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardSecurityCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPaymentPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(cardExpirationLabel)
                .addGap(18, 18, 18)
                .addComponent(cardMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardPaymentPanelLayout.setVerticalGroup(
            cardPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPaymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardSecurityCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(cardPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardExpirationLabel))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        paymentPanel.add(cardPaymentPanel, "cardCard");

        invoicePaymentPanel.setBackground(new java.awt.Color(229, 240, 255));
        invoicePaymentPanel.setToolTipText("Faktura betalning");

        personalNumberTextField.setText("ÅÅÅÅ-MM-DD-NNNN");

        personalNumberLabel.setBackground(new java.awt.Color(229, 240, 255));
        personalNumberLabel.setText("Personnummer");

        javax.swing.GroupLayout invoicePaymentPanelLayout = new javax.swing.GroupLayout(invoicePaymentPanel);
        invoicePaymentPanel.setLayout(invoicePaymentPanelLayout);
        invoicePaymentPanelLayout.setHorizontalGroup(
            invoicePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicePaymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personalNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personalNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        invoicePaymentPanelLayout.setVerticalGroup(
            invoicePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicePaymentPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(invoicePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personalNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personalNumberLabel))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        paymentPanel.add(invoicePaymentPanel, "invoiceCard");

        titleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Leveransadress");

        cardPaymentRadioButton.setBackground(new java.awt.Color(255, 252, 243));
        paymentRadioButtonGroup.add(cardPaymentRadioButton);
        cardPaymentRadioButton.setSelected(true);
        cardPaymentRadioButton.setText("Kortbetalning");
        cardPaymentRadioButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cardPaymentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardPaymentRadioButtonActionPerformed(evt);
            }
        });

        invoicePaymentRadioButton.setBackground(new java.awt.Color(255, 252, 243));
        paymentRadioButtonGroup.add(invoicePaymentRadioButton);
        invoicePaymentRadioButton.setText("Faktura");
        invoicePaymentRadioButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        invoicePaymentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoicePaymentRadioButtonActionPerformed(evt);
            }
        });

        deliveryEmailTextField.setEditable(false);
        deliveryEmailTextField.setNextFocusableComponent(cardPaymentRadioButton);

        deliveryPhoneTextField.setEditable(false);
        deliveryPhoneTextField.setNextFocusableComponent(deliveryEmailTextField);

        deliveryCityTextField.setEditable(false);
        deliveryCityTextField.setNextFocusableComponent(deliveryPhoneTextField);

        deliveryZipCodeTextField.setEditable(false);
        deliveryZipCodeTextField.setNextFocusableComponent(deliveryCityTextField);

        deliveryAdressTextField.setEditable(false);
        deliveryAdressTextField.setNextFocusableComponent(deliveryZipCodeTextField);

        deliveryLastNameTextField.setEditable(false);
        deliveryLastNameTextField.setNextFocusableComponent(deliveryAdressTextField);

        deliveryFirstNameTextField.setEditable(false);
        deliveryFirstNameTextField.setNextFocusableComponent(deliveryLastNameTextField);

        newAdressRadioButton.setBackground(new java.awt.Color(255, 252, 243));
        deliveryAdressRadioButtonGroup.add(newAdressRadioButton);
        newAdressRadioButton.setText("Ny adress");
        newAdressRadioButton.setNextFocusableComponent(sameAdressRadioButton.isSelected() ? cardPaymentRadioButton : deliveryFirstNameTextField);
        newAdressRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                newAdressRadioButtonItemStateChanged(evt);
            }
        });

        sameAdressRadioButton.setBackground(new java.awt.Color(255, 252, 243));
        deliveryAdressRadioButtonGroup.add(sameAdressRadioButton);
        sameAdressRadioButton.setSelected(true);
        sameAdressRadioButton.setText("Samma ");
        sameAdressRadioButton.setNextFocusableComponent(newAdressRadioButton);
        sameAdressRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sameAdressRadioButtonItemStateChanged(evt);
            }
        });

        deliveryFirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        deliveryFirstNameLabel.setText("Förnamn");

        deliveryLastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        deliveryLastNameLabel.setText("Efternamn");

        deliveryAdressLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        deliveryAdressLabel.setText("Adress");

        deliveryZipCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        deliveryZipCodeLabel.setText("Post nummer");

        deliveryCityLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        deliveryCityLabel.setText("Stad");

        deliveryPhoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        deliveryPhoneLabel.setText("Telefon nummer");

        deliveryEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        deliveryEmailLabel.setText("Epost");

        javax.swing.GroupLayout checkOutStage1PanelLayout = new javax.swing.GroupLayout(checkOutStage1Panel);
        checkOutStage1Panel.setLayout(checkOutStage1PanelLayout);
        checkOutStage1PanelLayout.setHorizontalGroup(
            checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                                .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(billingPhoneLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(billingCityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(billingAdressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(billingLastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(billingFirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(billingEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(billingZipCodeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(billingEmailTextField)
                                    .addComponent(billingLastNameTextField)
                                    .addComponent(billingAdressTextField)
                                    .addComponent(billingPhoneTextField)
                                    .addComponent(billingCityTextField)
                                    .addComponent(billingZipCodeTextField)
                                    .addComponent(billingFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                                .addComponent(sameAdressRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(newAdressRadioButton))
                            .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                                .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deliveryFirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deliveryLastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deliveryAdressLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(deliveryZipCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(deliveryCityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deliveryPhoneLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deliveryEmailLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deliveryEmailTextField)
                                    .addComponent(deliveryLastNameTextField)
                                    .addComponent(deliveryAdressTextField)
                                    .addComponent(deliveryPhoneTextField)
                                    .addComponent(deliveryCityTextField)
                                    .addComponent(deliveryZipCodeTextField)
                                    .addComponent(deliveryFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(billingTitleLabel)
                            .addComponent(titleLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutStage1PanelLayout.createSequentialGroup()
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutStage1PanelLayout.createSequentialGroup()
                                .addComponent(TotalPriceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalPriceNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutStage1PanelLayout.createSequentialGroup()
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(deliveryTimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(paymentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, checkOutStage1PanelLayout.createSequentialGroup()
                                .addComponent(cardPaymentRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(invoicePaymentRadioButton)))
                        .addGap(62, 62, 62))))
        );
        checkOutStage1PanelLayout.setVerticalGroup(
            checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(billingTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cardPaymentRadioButton)
                            .addComponent(invoicePaymentRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billingFirstNameLabel)
                            .addComponent(billingFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billingLastNameLabel)
                            .addComponent(billingLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billingAdressLabel)
                            .addComponent(billingAdressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billingZipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billingZipCodeLabel))
                        .addGap(6, 6, 6)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billingCityLabel)
                            .addComponent(billingCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billingPhoneLabel)
                            .addComponent(billingPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(billingEmailLabel)
                            .addComponent(billingEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                        .addComponent(deliveryTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalPriceLabel)
                            .addComponent(totalPriceNumberLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(checkOutStage1PanelLayout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newAdressRadioButton)
                            .addComponent(sameAdressRadioButton))
                        .addGap(18, 18, 18)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deliveryFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deliveryFirstNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deliveryLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deliveryLastNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deliveryAdressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deliveryAdressLabel))
                        .addGap(6, 6, 6)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deliveryZipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deliveryZipCodeLabel))
                        .addGap(6, 6, 6)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deliveryCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deliveryCityLabel))
                        .addGap(6, 6, 6)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deliveryPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deliveryPhoneLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkOutStage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deliveryEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deliveryEmailLabel))))
                .addGap(38, 38, 38))
        );

        add(checkOutStage1Panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        //places an order
        if(errorCheck()){
            JOptionPane.showMessageDialog(null, "Var god fyll i alla val.", "Fel i val", JOptionPane.ERROR_MESSAGE);
        }
        iMatShared.placeOrder();
        JOptionPane.showMessageDialog(null, "<html>Din order är bekräftad<br>"
                + "<br>"
                + "Din leverans kommer leveras:   " + (asSoonAsPossibleDeliveryRadioButton.isSelected() ? "Snarast" : dayOfDeliveryToString())
                +"<br>"
                + "Tidpunkt: " + timeOfDeliveryToString(), 
                "Order bekräftad", JOptionPane.PLAIN_MESSAGE);
        
    }//GEN-LAST:event_payButtonActionPerformed
    
    public String dayOfDeliveryToString(){
        return "Den " + dayDeliveryComboBox.getSelectedItem() + "/"+ monthDeliveryComboBox.getSelectedItem();
    }
    
    public Double totalPrice(){
        return iMatShared.getShoppingCart().getTotal();
    }
    /**
     * Checks that the combobox choices have been made. Returns true if default choices remains.
     * @return Boolean
    */
    public Boolean errorCheck(){
        
        if(chooseDayDeliveryRadioButton.isSelected()){
            if(dayDeliveryComboBox.getSelectedItem().equals("Dag")){
                return true;
            }else if(monthDeliveryComboBox.getSelectedItem().equals("Månad")){
                return true;
            }
        }else if(cardPaymentRadioButton.isSelected()){
            if(cardMonthComboBox.getSelectedItem().equals("Månad")){
                return true;
            }else if(cardYearComboBox.getSelectedItem().equals("Year")){
                return true;
            }
        }

        return false;
    }
    
    private String timeOfDeliveryToString(){
        if(morningDeliveryRadioButton.isSelected()){
            return "08-11";
        }else if(lunchDeliveryRadioButton.isSelected()){
            return "11-14";
        }else if(afternoonDeliveryRadioButton.isSelected()){
            return "14-17";
        }else{
            return "17-21";
        }
    }
    private void cardYearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardYearComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardYearComboBoxActionPerformed

    private void cardPaymentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardPaymentRadioButtonActionPerformed
        CardLayout cl = (CardLayout) (paymentPanel.getLayout());
        cl.show(paymentPanel, "cardCard");// TODO add your handling code here:
    }//GEN-LAST:event_cardPaymentRadioButtonActionPerformed

    private void invoicePaymentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoicePaymentRadioButtonActionPerformed
        CardLayout cl = (CardLayout) (paymentPanel.getLayout());
        cl.show(paymentPanel, "invoiceCard");// TODO add your handling code here:
    }//GEN-LAST:event_invoicePaymentRadioButtonActionPerformed
    
    private String getCardNumberText(){
        if(cc.getCardNumber() == null){
            
            cardNumberTextField.setForeground(Color.gray);
            return "Kortnummer";
        }
        else{
            
            cardNumberTextField.setForeground(Color.black);
            return cc.getCardNumber();
        }
    }
    private void billingFirstNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_billingFirstNameTextFieldFocusLost
        customer.setFirstName(billingFirstNameTextField.getText());
        if(sameAdressRadioButton.isSelected()){
            deliveryFirstNameTextField.setText(billingFirstNameTextField.getText());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_billingFirstNameTextFieldFocusLost

    private void billingLastNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_billingLastNameTextFieldFocusLost
        customer.setLastName(billingLastNameTextField.getText());
        if(sameAdressRadioButton.isSelected()){
            deliveryLastNameTextField.setText(billingLastNameTextField.getText());
        }
    }//GEN-LAST:event_billingLastNameTextFieldFocusLost

    private void billingZipCodeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_billingZipCodeTextFieldFocusLost
       customer.setPostCode(billingZipCodeTextField.getText());
        if(sameAdressRadioButton.isSelected()){
            deliveryZipCodeTextField.setText(billingZipCodeTextField.getText());
        } // TODO add your handling code here:
    }//GEN-LAST:event_billingZipCodeTextFieldFocusLost

    private void billingCityTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_billingCityTextFieldFocusLost
       customer.setPostAddress(billingCityTextField.getText());
        if(sameAdressRadioButton.isSelected()){
            deliveryCityTextField.setText(billingCityTextField.getText());
        } // TODO add your handling code here:
    }//GEN-LAST:event_billingCityTextFieldFocusLost

    private void billingPhoneTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_billingPhoneTextFieldFocusLost
       customer.setPhoneNumber(billingPhoneTextField.getText());
        if(sameAdressRadioButton.isSelected()){
            deliveryPhoneTextField.setText(billingPhoneTextField.getText());
        } // TODO add your handling code here:
    }//GEN-LAST:event_billingPhoneTextFieldFocusLost

    private void billingEmailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_billingEmailTextFieldFocusLost
        customer.setEmail(billingEmailTextField.getText());
        if(sameAdressRadioButton.isSelected()){
            deliveryEmailTextField.setText(billingEmailTextField.getText());
        }
    }//GEN-LAST:event_billingEmailTextFieldFocusLost
    
    
    
    private void newAdressRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_newAdressRadioButtonItemStateChanged
         if (evt.getStateChange() == ItemEvent.SELECTED) {
              deliveryFirstNameTextField.setEditable(true);
              deliveryLastNameTextField.setEditable(true);
              deliveryAdressTextField.setEditable(true);
              deliveryZipCodeTextField.setEditable(true);
              deliveryCityTextField.setEditable(true);
              deliveryPhoneTextField.setEditable(true);
              deliveryEmailTextField.setEditable(true);
              
              deliveryFirstNameTextField.setText("");
              deliveryLastNameTextField.setText("");
              deliveryAdressTextField.setText("");
              deliveryZipCodeTextField.setText("");
              deliveryCityTextField.setText("");
              deliveryPhoneTextField.setText("");
              deliveryEmailTextField.setText("");
              
        }        // TODO add your handling code here:
    }//GEN-LAST:event_newAdressRadioButtonItemStateChanged

    private void sameAdressRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sameAdressRadioButtonItemStateChanged
         if (evt.getStateChange() == ItemEvent.SELECTED) {
              deliveryFirstNameTextField.setEditable(false);
              deliveryLastNameTextField.setEditable(false);
              deliveryAdressTextField.setEditable(false);
              deliveryZipCodeTextField.setEditable(false);
              deliveryCityTextField.setEditable(false);
              deliveryPhoneTextField.setEditable(false);
              deliveryEmailTextField.setEditable(false);
              
              
              deliveryFirstNameTextField.setText(billingFirstNameTextField.getText());
              deliveryLastNameTextField.setText(billingLastNameTextField.getText());
              deliveryAdressTextField.setText(billingAdressTextField.getText());
              deliveryZipCodeTextField.setText(billingZipCodeTextField.getText());
              deliveryCityTextField.setText(billingCityTextField.getText());
              deliveryPhoneTextField.setText(billingPhoneTextField.getText());
              deliveryEmailTextField.setText(billingEmailTextField.getText());
              
         }              // TODO add your handling code here:
    }//GEN-LAST:event_sameAdressRadioButtonItemStateChanged

    private void billingAdressTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_billingAdressTextFieldFocusLost
        customer.setAddress(billingAdressTextField.getText());
        if(sameAdressRadioButton.isSelected()){
            deliveryAdressTextField.setText(billingAdressTextField.getText());
        }// TODO add your handling code here:
    }//GEN-LAST:event_billingAdressTextFieldFocusLost

    private void cardNumberTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardNumberTextFieldFocusGained
        cardNumberTextField.setText(cc.getCardNumber());
        cardNumberTextField.setForeground(Color.black);
        
    }//GEN-LAST:event_cardNumberTextFieldFocusGained

    private void cardNumberTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardNumberTextFieldFocusLost
        cc.setCardNumber(cardNumberTextField.getText());
        cardNumberTextField.setText("******KORTNUMMER*****");// TODO add your handling code here:
    }//GEN-LAST:event_cardNumberTextFieldFocusLost

    private void cardSecurityCodeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardSecurityCodeTextFieldFocusGained
       cardSecurityCodeTextField.setText("" + cc.getVerificationCode());        // TODO add your handling code here:
    }//GEN-LAST:event_cardSecurityCodeTextFieldFocusGained

    private void cardSecurityCodeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardSecurityCodeTextFieldFocusLost
       try{
           cc.setVerificationCode(Integer.parseInt(cardSecurityCodeTextField.getText()));
       }catch(IllegalArgumentException e){
           
       }
       cardSecurityCodeTextField.setText("***CVV****");    // TODO add your handling code here:
    }//GEN-LAST:event_cardSecurityCodeTextFieldFocusLost

    public  JLabel getTotalPriceNumberLabel(){
        return totalPriceNumberLabel;
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TotalPriceLabel;
    private javax.swing.JRadioButton afternoonDeliveryRadioButton;
    private javax.swing.JLabel afternoonLabel;
    private javax.swing.JRadioButton asSoonAsPossibleDeliveryRadioButton;
    private javax.swing.JLabel billingAdressLabel;
    private javax.swing.JTextField billingAdressTextField;
    private javax.swing.JLabel billingCityLabel;
    private javax.swing.JTextField billingCityTextField;
    private javax.swing.JLabel billingEmailLabel;
    private javax.swing.JTextField billingEmailTextField;
    private javax.swing.JLabel billingFirstNameLabel;
    private javax.swing.JTextField billingFirstNameTextField;
    private javax.swing.JLabel billingLastNameLabel;
    private javax.swing.JTextField billingLastNameTextField;
    private javax.swing.JLabel billingPhoneLabel;
    private javax.swing.JTextField billingPhoneTextField;
    private javax.swing.JLabel billingTitleLabel;
    private javax.swing.JLabel billingZipCodeLabel;
    private javax.swing.JTextField billingZipCodeTextField;
    private javax.swing.JLabel cardExpirationLabel;
    private javax.swing.JComboBox cardMonthComboBox;
    private javax.swing.JTextField cardNumberTextField;
    private javax.swing.JPanel cardPaymentPanel;
    private javax.swing.JRadioButton cardPaymentRadioButton;
    private javax.swing.JTextField cardSecurityCodeTextField;
    private javax.swing.JComboBox cardYearComboBox;
    private javax.swing.JPanel checkOutStage1Panel;
    private javax.swing.JRadioButton chooseDayDeliveryRadioButton;
    private javax.swing.JComboBox dayDeliveryComboBox;
    private javax.swing.ButtonGroup dayOfDeliveryRadioButtonGroup;
    private javax.swing.JLabel deliveryAdressLabel;
    private javax.swing.ButtonGroup deliveryAdressRadioButtonGroup;
    private javax.swing.JTextField deliveryAdressTextField;
    private javax.swing.JLabel deliveryCityLabel;
    private javax.swing.JTextField deliveryCityTextField;
    private javax.swing.JLabel deliveryDayLabel;
    private javax.swing.JLabel deliveryEmailLabel;
    private javax.swing.JTextField deliveryEmailTextField;
    private javax.swing.JLabel deliveryFirstNameLabel;
    private javax.swing.JTextField deliveryFirstNameTextField;
    private javax.swing.JLabel deliveryLastNameLabel;
    private javax.swing.JTextField deliveryLastNameTextField;
    private javax.swing.JLabel deliveryPhoneLabel;
    private javax.swing.JTextField deliveryPhoneTextField;
    private javax.swing.JPanel deliveryTimePanel;
    private javax.swing.JLabel deliveryZipCodeLabel;
    private javax.swing.JTextField deliveryZipCodeTextField;
    private javax.swing.JLabel eveningLabel;
    private javax.swing.JRadioButton eveningRadioButton;
    private javax.swing.JPanel invoicePaymentPanel;
    private javax.swing.JRadioButton invoicePaymentRadioButton;
    private javax.swing.JRadioButton lunchDeliveryRadioButton;
    private javax.swing.JLabel lunchLabel;
    private javax.swing.JComboBox monthDeliveryComboBox;
    private javax.swing.JRadioButton morningDeliveryRadioButton;
    private javax.swing.JLabel morningLabel;
    private javax.swing.JRadioButton newAdressRadioButton;
    private javax.swing.JButton payButton;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.ButtonGroup paymentRadioButtonGroup;
    private javax.swing.JLabel personalNumberLabel;
    private javax.swing.JTextField personalNumberTextField;
    private javax.swing.JRadioButton sameAdressRadioButton;
    private javax.swing.JLabel timeOfDayLabel;
    private javax.swing.ButtonGroup timeOfDayRadioButtonGroup;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalPriceNumberLabel;
    // End of variables declaration//GEN-END:variables
}
