    import java.awt.Color;
import java.awt.event.ActionListener;
import se.chalmers.ait.dat215.project.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erik
 */
public class itemPanel extends javax.swing.JPanel {
    IMatDataHandler dh = IMatDataHandler.getInstance();
    Product p;
    /**
     * Creates new form itemPanel
     */
    public itemPanel() {
        initComponents();
    }
    public itemPanel(Product p, Boolean r, ActionListener al){
        
        this.p = p;
        initComponents();
        if(!r)
            setBackground(new Color(0xe5,0xf0,0xff));
        else
            setBackground(new Color(0xf4,0xf6,0xff));
        
        iconButton.setIcon(dh.getImageIcon(p, 48, 48));
        iconButton.setBackground(this.getBackground());
        nameButton.setText(p.getName());
        nameButton.setBackground(this.getBackground());
        unitLabel.setText(p.getUnitSuffix());
        priceLabel.setText(p.getPrice() + p.getUnit());
        addToCartButton.addActionListener(al);
        starButton.addActionListener(al);
        if(dh.isFavorite(p))
            starButton.setIcon(new javax.swing.ImageIcon("pictures/starFilled.png"));
        
        
    }
    public Product getProduct(){
        return p;
    }
    public Double getAmount(){
        double d = Integer.parseInt(amountTextField.getText());
        return  d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconButton = new javax.swing.JButton();
        nameButton = new javax.swing.JButton();
        incrementButton = new javax.swing.JButton();
        decrementButton = new javax.swing.JButton();
        amountTextField = new javax.swing.JTextField();
        unitLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        starButton = new javax.swing.JButton();
        moreButton = new javax.swing.JButton();
        addToCartButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(677, 52));

        iconButton.setBorder(null);
        iconButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        iconButton.setMaximumSize(new java.awt.Dimension(64, 64));
        iconButton.setMinimumSize(new java.awt.Dimension(48, 48));
        iconButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        iconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconButtonActionPerformed(evt);
            }
        });

        nameButton.setText("name");
        nameButton.setBorder(null);
        nameButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        incrementButton.setBackground(new java.awt.Color(255, 255, 255));
        incrementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrowUp.png"))); // NOI18N
        incrementButton.setMaximumSize(new java.awt.Dimension(16, 16));
        incrementButton.setMinimumSize(new java.awt.Dimension(16, 16));
        incrementButton.setPreferredSize(new java.awt.Dimension(16, 16));
        incrementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrementButtonActionPerformed(evt);
            }
        });

        decrementButton.setBackground(new java.awt.Color(255, 255, 255));
        decrementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrowDown.png"))); // NOI18N
        decrementButton.setMaximumSize(new java.awt.Dimension(16, 16));
        decrementButton.setMinimumSize(new java.awt.Dimension(16, 16));
        decrementButton.setPreferredSize(new java.awt.Dimension(16, 16));
        decrementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrementButtonActionPerformed(evt);
            }
        });

        amountTextField.setText("1");
        amountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextFieldActionPerformed(evt);
            }
        });

        unitLabel.setText("unit");

        priceLabel.setText("price");

        starButton.setBackground(new java.awt.Color(255, 255, 255));
        starButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/starEmpty.png"))); // NOI18N
        starButton.setActionCommand("Star");
        starButton.setBorderPainted(false);
        starButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starButtonActionPerformed(evt);
            }
        });

        moreButton.setText("Mer");

        addToCartButton.setText("Lägg till");
        addToCartButton.setActionCommand("Lägg till");
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(iconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incrementButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decrementButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(unitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(starButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moreButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToCartButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(incrementButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(decrementButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(priceLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(unitLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(amountTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(starButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(moreButton)
                                            .addComponent(addToCartButton)))))))
                    .addComponent(iconButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void starButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starButtonActionPerformed
        if(!dh.isFavorite(p)){
            dh.addFavorite(p);
            starButton.setIcon(new javax.swing.ImageIcon("pictures/starFilled.png"));
        }else{
            dh.removeFavorite(p);
            starButton.setIcon(new javax.swing.ImageIcon("pictures/starEmpty.png"));
        }
    
    }//GEN-LAST:event_starButtonActionPerformed

    private void amountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTextFieldActionPerformed

    private void incrementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrementButtonActionPerformed
       int i = 0;
       String s = amountTextField.getText();
       try{
           i = Integer.parseInt(s);
       }catch(NumberFormatException e){
           //Will set ammount to 1
       }
       i++;
       amountTextField.setText(Integer.toString(i));
    }//GEN-LAST:event_incrementButtonActionPerformed

    private void decrementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrementButtonActionPerformed
       int i = 1;
       String s = amountTextField.getText();
       try{
           i = Integer.parseInt(s);
           i--;
       }catch(NumberFormatException e){
           
       }
    
       if(i > 0)
            amountTextField.setText(Integer.toString(i));
    }//GEN-LAST:event_decrementButtonActionPerformed

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed
        amountTextField.setText("1");
    }//GEN-LAST:event_addToCartButtonActionPerformed

    private void iconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconButtonActionPerformed
       // iconButton.setIcon(dh.getImageIcon(p,64,64));
    }//GEN-LAST:event_iconButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartButton;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JButton decrementButton;
    private javax.swing.JButton iconButton;
    private javax.swing.JButton incrementButton;
    private javax.swing.JButton moreButton;
    private javax.swing.JButton nameButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton starButton;
    private javax.swing.JLabel unitLabel;
    // End of variables declaration//GEN-END:variables
}
