
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.*;
import javax.swing.JPanel;
import se.chalmers.ait.dat215.project.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administratör
 */
public class ShoppingCartPanel extends javax.swing.JPanel {

    /**
     * Creates new form shoppingCartPanel
     */
    public ShoppingCartPanel() {
        initComponents();
    }
    public ShoppingCartPanel(ShoppingCart cartList){
        this();
        totalSumLabel.setText(String.valueOf(cartList.getTotal()));
        List<ShoppingItem> listItems= cartList.getItems();
        for( ShoppingItem shoppingItem: listItems ){
            cartHolderPanel.add(new SingleListItem(shoppingItem,true));
        }
        
    }
    
    public void updateShoppingCartPanel(ShoppingCart cartList){
        cartHolderPanel.removeAll();
        totalSumLabel.setText(String.valueOf(Math.round(cartList.getTotal()*100)/100.0));
        List<ShoppingItem> listItems= cartList.getItems();
        for( ShoppingItem shoppingItem: listItems ){
            cartHolderPanel.add(new SingleListItem(shoppingItem,true));
        }
        if(listItems.size() < 14){
            System.err.println(listItems.size() + "less than 14");
            for(int i = listItems.size(); i < 14; i++)
                cartHolderPanel.add(new invisiblePanel());
        }
        
    }
    public void setActionListener(ActionListener al){
        checkoutCartButton.addActionListener(al);
        clearCartButton.addActionListener(al);
        saveCartButton.addActionListener(al);
    }
   private class invisiblePanel extends JPanel{
        public invisiblePanel(){
            setSize(100, 25);
            setVisible(true);
            setBackground(new Color(0xe5,0xf0,0xff));
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clearCartButton = new javax.swing.JButton();
        saveCartButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        totalSumLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cartNameLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        checkoutCartButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartHolderPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 252, 243));
        setMinimumSize(new java.awt.Dimension(200, 630));
        setPreferredSize(new java.awt.Dimension(200, 630));

        clearCartButton.setText("Rensa");
        clearCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearCartButtonActionPerformed(evt);
            }
        });

        saveCartButton.setText("Spara");

        totalSumLabel.setText("jLabel1");

        jLabel2.setText("Totalsumma:");

        cartNameLabel.setText("Kundvagn");

        checkoutCartButton.setText("Till kassa");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        cartHolderPanel.setBackground(new java.awt.Color(229, 240, 255));
        cartHolderPanel.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(cartHolderPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(checkoutCartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveCartButton, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearCartButton, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cartNameLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalSumLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cartNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalSumLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearCartButton)
                    .addComponent(saveCartButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(checkoutCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clearCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearCartButtonActionPerformed
        
    }//GEN-LAST:event_clearCartButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cartHolderPanel;
    private javax.swing.JLabel cartNameLabel;
    private javax.swing.JButton checkoutCartButton;
    private javax.swing.JButton clearCartButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton saveCartButton;
    private javax.swing.JLabel totalSumLabel;
    // End of variables declaration//GEN-END:variables
}
